### ISSUE TITLE
报错 Unable to find image

### ISSUE THREAD

**Issue by tossp** [saltbo/uptoc#28]
是我哪里没配置对吗

https://github.com/tossp/build-openwrt/actions/runs/664255429/workflow

```
Run saltbo/uptoc@master
  with:
    driver: qiniu
    region: cn-south-1
    bucket: lede-k3
    exclude: .cache,test
    dist: /home/runner/work/build-openwrt/build-openwrt/openwrt/bin/targets/bcm53xx/generic
  env:
    LEDE: https://github.com/coolsnowwolf/lede
    LIENOL: https://github.com/Lienol/openwrt
    PROJECT: https://github.com/immortalwrt/immortalwrt
    GITURL: https://github.com/tossp/build-openwrt
    TZ: Asia/Shanghai
    Modelfile: Lede_phicomm_k3
    Author: tossp
    REPO_URL: https://github.com/coolsnowwolf/lede
    REPO_BRANCH: master
    CONFIG_FILE: .config
    DIY_P1_SH: diy-1.sh
    DIY_P2_SH: diy-2.sh
    SSH_ACTIONS: false
    UPLOAD_BIN_DIR: false
    UPLOAD_CONFIG: true
    UPLOAD_FIRMWARE: true
    UPLOAD_COWTRANSFER: true
    UPLOAD_QN: true
    UPLOAD_RELEASE: false
    SERVERCHAN_SCKEY: false
    REGULAR_UPDATE: true
    Updete_firmware: 
    Extension: 
    Home: /home/runner/work/build-openwrt/build-openwrt/openwrt
    PATH1: /home/runner/work/build-openwrt/build-openwrt/openwrt/build/Lede_phicomm_k3
    artifact: /home/runner/work/build-openwrt/build-openwrt/openwrt/bin/Firmware
    NAME2: Lede
    ZUOZHE: Lean's
    date: 21.03.18-2033
    date2: 20210318203317
    NAME1: phicomm-k3
    FIRMWARE: /home/runner/work/build-openwrt/build-openwrt/openwrt/bin/targets/bcm53xx/generic
    BOT: TRUE
    UPTOC_UPLOADER_AK: ***
    UPTOC_UPLOADER_SK: ***
/usr/bin/docker run --name e4972c0289a2d047b088f246d87ac7a22e_e9f5bd --label 5588e4 --workdir /github/workspace --rm -e LEDE -e LIENOL -e PROJECT -e GITURL -e TZ -e Modelfile -e Author -e REPO_URL -e REPO_BRANCH -e CONFIG_FILE -e DIY_P1_SH -e DIY_P2_SH -e SSH_ACTIONS -e UPLOAD_BIN_DIR -e UPLOAD_CONFIG -e UPLOAD_FIRMWARE -e UPLOAD_COWTRANSFER -e UPLOAD_QN -e UPLOAD_RELEASE -e SERVERCHAN_SCKEY -e REGULAR_UPDATE -e Updete_firmware -e Extension -e Home -e PATH1 -e artifact -e NAME2 -e ZUOZHE -e date -e date2 -e NAME1 -e FIRMWARE -e BOT -e UPTOC_UPLOADER_AK -e UPTOC_UPLOADER_SK -e INPUT_DRIVER -e INPUT_REGION -e INPUT_BUCKET -e INPUT_EXCLUDE -e INPUT_DIST -e INPUT_SAVEROOT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/build-openwrt/build-openwrt":"/github/workspace" 5588e4:972c0289a2d047b088f246d87ac7a22e
Unable to find image '5588e4:972c0289a2d047b088f246d87ac7a22e' locally
docker: Error response from daemon: pull access denied for 5588e4, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
